image: fpco/stack-build:lts-11.6

cache:
  paths:
    - .stack-work

build:
  script:
     - stack build

test:
  script:
     - stack test

# deploy:
#   script:
#     - stack install
#   only:
#     - master
