image: fpco/stack-build:lts-11.6

variables:
  STACK_ROOT: "$CI_PROJECT_DIR/.stack"

cache:
  paths:
    - .stack-work
    - .stack

build:
  script:
     - stack build

test:
  script:
     - stack test

# deploy:
#   script:
#     - stack install
#   only:
#     - master
