name:                xrn
version:             0.1.0.0
github:              "githubuser/xrn"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/xrn#readme>

dependencies:
# - haskell-abci
- aeson
- base
- classy-prelude
- data-default
- haskell-lsp
- hslogger
- hslua
- language-ecmascript
- lens
- megaparsec
- mtl
- optparse-applicative
- prettyprinter
- simple-smt
- sourcemap
- stm
- string-conversions
- text
- type-fun
- unordered-containers
- vector
- yi-rope

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - OverloadedStrings
  - Rank2Types
  - RankNTypes
  - ScopedTypeVariables
  - TypeOperators
  - TypeSynonymInstances
  - GADTs
  - BangPatterns
  - FunctionalDependencies
  - DuplicateRecordFields
  - RecordWildCards
  - NamedFieldPuns
  - PatternGuards
  - PolyKinds
  - DeriveGeneric
  - MultiWayIf

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns 
    - -Wredundant-constraints 

executables:
  xrn:
    main:                Main.hs
    source-dirs:         app/xrn
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xrn

  ceres:
    main:                Main.hs
    source-dirs:         app/ceres
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xrn

tests:
  xrn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xrn
