resolver: lts-11.3
allow-newer: true
packages:
- .
extra-deps:
# - base-noprelude-4.10.1.0
- liquid-fixpoint-0.7.0.7
- located-base-0.1.1.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
nix:
  enable: true
  packages: [z3]
